version: "3.8"

services:
  app:
    container_name: counter_app
    build: ./ 
    depends_on:
      - db
    command: bash -c '/wait-for-it.sh postgres:5432 -- uvicorn app.main:app --host 0.0.0.0 --port 8000'
    volumes:
      - ./app:/src/app
      - ./database:/src/database
      - ./wait-for-it.sh:/wait-for-it.sh
    ports:
      - 8001:8000
    restart: always
    env_file:
      - .env
  db:
    container_name: counter_db
    image: postgres
    environment:
      - POSTGRES_DB="counter_db"
      - POSTGRES_USER="counter_user"
      - POSTGRES_PASSWORD="ThePassw0rD"
    ports:
      - 5431:5432
    volumes:
      - .postgres:/var/lib/postgres/data
    restart: always
